auth0:
  audience: http://localhost:8080
spring:
  security:
    oauth2:
        resourceserver:
            jwt:
                issuer-uri: https://dev-ox3h99pl.us.auth0.com/
                jwk-set-uri: https://dev-ox3h99pl.us.auth0.com/.well-known/jwks.json